/* Generated by scripts/prepare_media.py. */
export const mediaBySlug = {
  "ventile-armaturen": [
    {
      "src": "/media/ventile-armaturen/01-1280.webp",
      "thumb": "/media/ventile-armaturen/01-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 01",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/02-1280.webp",
      "thumb": "/media/ventile-armaturen/02-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 02",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/03-1280.webp",
      "thumb": "/media/ventile-armaturen/03-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 03",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/04-1280.webp",
      "thumb": "/media/ventile-armaturen/04-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 04",
      "width": 1086,
      "height": 1449
    },
    {
      "src": "/media/ventile-armaturen/05-1280.webp",
      "thumb": "/media/ventile-armaturen/05-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 05",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/06-1280.webp",
      "thumb": "/media/ventile-armaturen/06-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 06",
      "width": 1085,
      "height": 1450
    },
    {
      "src": "/media/ventile-armaturen/07-1280.webp",
      "thumb": "/media/ventile-armaturen/07-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 07",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/08-1280.webp",
      "thumb": "/media/ventile-armaturen/08-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 08",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/09-1280.webp",
      "thumb": "/media/ventile-armaturen/09-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 09",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/10-1280.webp",
      "thumb": "/media/ventile-armaturen/10-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 10",
      "width": 1280,
      "height": 720
    },
    {
      "src": "/media/ventile-armaturen/11-1280.webp",
      "thumb": "/media/ventile-armaturen/11-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 11",
      "width": 1280,
      "height": 720
    },
    {
      "src": "/media/ventile-armaturen/12-1280.webp",
      "thumb": "/media/ventile-armaturen/12-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 12",
      "width": 1280,
      "height": 958
    },
    {
      "src": "/media/ventile-armaturen/13-1280.webp",
      "thumb": "/media/ventile-armaturen/13-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 13",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/ventile-armaturen/14-1280.webp",
      "thumb": "/media/ventile-armaturen/14-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 14",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/15-1280.webp",
      "thumb": "/media/ventile-armaturen/15-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 15",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/ventile-armaturen/16-1280.webp",
      "thumb": "/media/ventile-armaturen/16-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 16",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/ventile-armaturen/17-1280.webp",
      "thumb": "/media/ventile-armaturen/17-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 17",
      "width": 1280,
      "height": 720
    },
    {
      "src": "/media/ventile-armaturen/18-1280.webp",
      "thumb": "/media/ventile-armaturen/18-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 18",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/ventile-armaturen/19-1280.webp",
      "thumb": "/media/ventile-armaturen/19-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 19",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/20-1280.webp",
      "thumb": "/media/ventile-armaturen/20-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 20",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/21-1280.webp",
      "thumb": "/media/ventile-armaturen/21-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 21",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ventile-armaturen/22-1280.webp",
      "thumb": "/media/ventile-armaturen/22-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 22",
      "width": 1280,
      "height": 958
    },
    {
      "src": "/media/ventile-armaturen/23-1280.webp",
      "thumb": "/media/ventile-armaturen/23-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 23",
      "width": 1086,
      "height": 1448
    },
    {
      "src": "/media/ventile-armaturen/24-1280.webp",
      "thumb": "/media/ventile-armaturen/24-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 24",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/ventile-armaturen/25-1280.webp",
      "thumb": "/media/ventile-armaturen/25-480.webp",
      "alt": "Massgefertigte Ventil- und Armaturenisolierung – Referenz 25",
      "width": 1024,
      "height": 768
    }
  ],
  "heizungszentralen": [
    {
      "src": "/media/heizungszentralen/01-1280.webp",
      "thumb": "/media/heizungszentralen/01-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 01",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/heizungszentralen/02-1280.webp",
      "thumb": "/media/heizungszentralen/02-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 02",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/heizungszentralen/03-1280.webp",
      "thumb": "/media/heizungszentralen/03-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 03",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/heizungszentralen/04-1280.webp",
      "thumb": "/media/heizungszentralen/04-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 04",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/heizungszentralen/05-1280.webp",
      "thumb": "/media/heizungszentralen/05-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 05",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/heizungszentralen/06-1280.webp",
      "thumb": "/media/heizungszentralen/06-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 06",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/heizungszentralen/07-1280.webp",
      "thumb": "/media/heizungszentralen/07-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 07",
      "width": 1280,
      "height": 1707
    },
    {
      "src": "/media/heizungszentralen/08-1280.webp",
      "thumb": "/media/heizungszentralen/08-480.webp",
      "alt": "Dämmkissen in einer Heizungszentrale – Referenz 08",
      "width": 1280,
      "height": 960
    }
  ],
  "ascheaustragssysteme": [
    {
      "src": "/media/ascheaustragssysteme/01-1280.webp",
      "thumb": "/media/ascheaustragssysteme/01-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 01",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ascheaustragssysteme/02-1280.webp",
      "thumb": "/media/ascheaustragssysteme/02-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 02",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/ascheaustragssysteme/03-1280.webp",
      "thumb": "/media/ascheaustragssysteme/03-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 03",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ascheaustragssysteme/04-1280.webp",
      "thumb": "/media/ascheaustragssysteme/04-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 04",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/ascheaustragssysteme/05-1280.webp",
      "thumb": "/media/ascheaustragssysteme/05-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 05",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/ascheaustragssysteme/06-1280.webp",
      "thumb": "/media/ascheaustragssysteme/06-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 06",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/ascheaustragssysteme/07-1280.webp",
      "thumb": "/media/ascheaustragssysteme/07-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 07",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/ascheaustragssysteme/08-1280.webp",
      "thumb": "/media/ascheaustragssysteme/08-480.webp",
      "alt": "Isolierung an einem Ascheaustragssystem – Referenz 08",
      "width": 1280,
      "height": 956
    }
  ],
  "revisionstueren": [
    {
      "src": "/media/revisionstueren/01-1280.webp",
      "thumb": "/media/revisionstueren/01-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 01",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/revisionstueren/02-1280.webp",
      "thumb": "/media/revisionstueren/02-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 02",
      "width": 1280,
      "height": 1707
    },
    {
      "src": "/media/revisionstueren/03-1280.webp",
      "thumb": "/media/revisionstueren/03-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 03",
      "width": 1280,
      "height": 1707
    },
    {
      "src": "/media/revisionstueren/04-1280.webp",
      "thumb": "/media/revisionstueren/04-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 04",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/revisionstueren/05-1280.webp",
      "thumb": "/media/revisionstueren/05-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 05",
      "width": 1280,
      "height": 1707
    },
    {
      "src": "/media/revisionstueren/06-1280.webp",
      "thumb": "/media/revisionstueren/06-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 06",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/revisionstueren/07-1280.webp",
      "thumb": "/media/revisionstueren/07-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 07",
      "width": 1280,
      "height": 1707
    },
    {
      "src": "/media/revisionstueren/08-1280.webp",
      "thumb": "/media/revisionstueren/08-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 08",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/revisionstueren/09-1280.webp",
      "thumb": "/media/revisionstueren/09-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 09",
      "width": 1280,
      "height": 2276
    },
    {
      "src": "/media/revisionstueren/10-1280.webp",
      "thumb": "/media/revisionstueren/10-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 10",
      "width": 1280,
      "height": 720
    },
    {
      "src": "/media/revisionstueren/11-1280.webp",
      "thumb": "/media/revisionstueren/11-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 11",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/revisionstueren/12-1280.webp",
      "thumb": "/media/revisionstueren/12-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 12",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/revisionstueren/13-1280.webp",
      "thumb": "/media/revisionstueren/13-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 13",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/revisionstueren/14-1280.webp",
      "thumb": "/media/revisionstueren/14-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 14",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/revisionstueren/15-1280.webp",
      "thumb": "/media/revisionstueren/15-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 15",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/revisionstueren/16-1280.webp",
      "thumb": "/media/revisionstueren/16-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 16",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/revisionstueren/17-1280.webp",
      "thumb": "/media/revisionstueren/17-480.webp",
      "alt": "Abnehmbare Isolierung einer Revisionstür – Referenz 17",
      "width": 1280,
      "height": 1714
    }
  ],
  "kompensatoren": [
    {
      "src": "/media/kompensatoren/01-1280.webp",
      "thumb": "/media/kompensatoren/01-480.webp",
      "alt": "Dämmkissen an einem Kompensator – Referenz 01",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/kompensatoren/02-1280.webp",
      "thumb": "/media/kompensatoren/02-480.webp",
      "alt": "Dämmkissen an einem Kompensator – Referenz 02",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/kompensatoren/03-1280.webp",
      "thumb": "/media/kompensatoren/03-480.webp",
      "alt": "Dämmkissen an einem Kompensator – Referenz 03",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/media/kompensatoren/04-1280.webp",
      "thumb": "/media/kompensatoren/04-480.webp",
      "alt": "Dämmkissen an einem Kompensator – Referenz 04",
      "width": 768,
      "height": 1024
    },
    {
      "src": "/media/kompensatoren/05-1280.webp",
      "thumb": "/media/kompensatoren/05-480.webp",
      "alt": "Dämmkissen an einem Kompensator – Referenz 05",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/kompensatoren/06-1280.webp",
      "thumb": "/media/kompensatoren/06-480.webp",
      "alt": "Dämmkissen an einem Kompensator – Referenz 06",
      "width": 1280,
      "height": 1714
    }
  ],
  "turbinen": [
    {
      "src": "/media/turbinen/01-1280.webp",
      "thumb": "/media/turbinen/01-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 01",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/turbinen/02-1280.webp",
      "thumb": "/media/turbinen/02-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 02",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/turbinen/03-1280.webp",
      "thumb": "/media/turbinen/03-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 03",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/turbinen/04-1280.webp",
      "thumb": "/media/turbinen/04-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 04",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/turbinen/05-1280.webp",
      "thumb": "/media/turbinen/05-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 05",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/turbinen/06-1280.webp",
      "thumb": "/media/turbinen/06-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 06",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/media/turbinen/07-1280.webp",
      "thumb": "/media/turbinen/07-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 07",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/turbinen/08-1280.webp",
      "thumb": "/media/turbinen/08-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 08",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/turbinen/09-1280.webp",
      "thumb": "/media/turbinen/09-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 09",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/turbinen/10-1280.webp",
      "thumb": "/media/turbinen/10-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 10",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/turbinen/11-1280.webp",
      "thumb": "/media/turbinen/11-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 11",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/turbinen/12-1280.webp",
      "thumb": "/media/turbinen/12-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 12",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/turbinen/13-1280.webp",
      "thumb": "/media/turbinen/13-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 13",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/turbinen/14-1280.webp",
      "thumb": "/media/turbinen/14-480.webp",
      "alt": "Modulare Turbinenisolierung – Referenz 14",
      "width": 1224,
      "height": 1632
    }
  ],
  "sonderbau": [
    {
      "src": "/media/sonderbau/01-1280.webp",
      "thumb": "/media/sonderbau/01-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 01",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/sonderbau/02-1280.webp",
      "thumb": "/media/sonderbau/02-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 02",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/sonderbau/03-1280.webp",
      "thumb": "/media/sonderbau/03-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 03",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/sonderbau/04-1280.webp",
      "thumb": "/media/sonderbau/04-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 04",
      "width": 1280,
      "height": 720
    },
    {
      "src": "/media/sonderbau/05-1280.webp",
      "thumb": "/media/sonderbau/05-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 05",
      "width": 1280,
      "height": 2276
    },
    {
      "src": "/media/sonderbau/06-1280.webp",
      "thumb": "/media/sonderbau/06-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 06",
      "width": 1280,
      "height": 720
    },
    {
      "src": "/media/sonderbau/07-1280.webp",
      "thumb": "/media/sonderbau/07-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 07",
      "width": 1280,
      "height": 720
    },
    {
      "src": "/media/sonderbau/08-1280.webp",
      "thumb": "/media/sonderbau/08-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 08",
      "width": 1086,
      "height": 1448
    },
    {
      "src": "/media/sonderbau/09-1280.webp",
      "thumb": "/media/sonderbau/09-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 09",
      "width": 1086,
      "height": 1448
    },
    {
      "src": "/media/sonderbau/10-1280.webp",
      "thumb": "/media/sonderbau/10-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 10",
      "width": 1280,
      "height": 1707
    },
    {
      "src": "/media/sonderbau/11-1280.webp",
      "thumb": "/media/sonderbau/11-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 11",
      "width": 1024,
      "height": 768
    },
    {
      "src": "/media/sonderbau/12-1280.webp",
      "thumb": "/media/sonderbau/12-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 12",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/13-1280.webp",
      "thumb": "/media/sonderbau/13-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 13",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/14-1280.webp",
      "thumb": "/media/sonderbau/14-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 14",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/15-1280.webp",
      "thumb": "/media/sonderbau/15-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 15",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/sonderbau/16-1280.webp",
      "thumb": "/media/sonderbau/16-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 16",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/17-1280.webp",
      "thumb": "/media/sonderbau/17-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 17",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/18-1280.webp",
      "thumb": "/media/sonderbau/18-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 18",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/sonderbau/19-1280.webp",
      "thumb": "/media/sonderbau/19-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 19",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/20-1280.webp",
      "thumb": "/media/sonderbau/20-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 20",
      "width": 1280,
      "height": 1714
    },
    {
      "src": "/media/sonderbau/21-1280.webp",
      "thumb": "/media/sonderbau/21-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 21",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/22-1280.webp",
      "thumb": "/media/sonderbau/22-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 22",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/23-1280.webp",
      "thumb": "/media/sonderbau/23-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 23",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/24-1280.webp",
      "thumb": "/media/sonderbau/24-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 24",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/25-1280.webp",
      "thumb": "/media/sonderbau/25-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 25",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/26-1280.webp",
      "thumb": "/media/sonderbau/26-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 26",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/27-1280.webp",
      "thumb": "/media/sonderbau/27-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 27",
      "width": 1280,
      "height": 960
    },
    {
      "src": "/media/sonderbau/28-1280.webp",
      "thumb": "/media/sonderbau/28-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 28",
      "width": 1280,
      "height": 956
    },
    {
      "src": "/media/sonderbau/29-1280.webp",
      "thumb": "/media/sonderbau/29-480.webp",
      "alt": "Individuelle Sonderisolierung – Referenz 29",
      "width": 1280,
      "height": 956
    }
  ]
} as const
